### ISSUE TITLE
👨‍🦲 Topic

### ISSUE THREAD

**Issue by nerap** [nerap/brokust#17]
# Topic workflow

- [ ] Client Request: Create a topic my-topic with 3 partitions and a replication factor of 2. #5 
- [ ] Controller Broker: Decides partition 0 is on broker 1 (leader) and broker 2 (follower), partition 1 is on broker 2 (leader) and broker 3 (follower), partition 2 is on broker 3 (leader) and broker 1 (follower). #10 #11 
- [ ] Zookeeper Update: Metadata for my-topic with partition assignments is stored in Zookeeper. #15 #11 
- [ ] Broker Setup: Brokers 1, 2, and 3 prepare to host their respective partitions. #10 #16 
- [ ] Replication: Broker 1 (leader for partition 0) starts replicating data to broker 2 (follower for partition 0), and so on for the other partitions.
- [ ] Topic Availability: Producers can now send messages to my-topic, and consumers can read from it. #4
